# Generated by Django 3.2.5 on 2021-07-14 22:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=64, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 18, 22, 45, 62551), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Вопрос'),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_desc', models.CharField(max_length=32)),
                ('digital_desc', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.answer')),
            ],
        ),
    ]
