# Generated by Django 3.2.5 on 2021-07-15 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210714_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 20, 59, 34, 146727)),
        ),
    ]
